### ISSUE TITLE
Sugestào de paleta de cores

### ISSUE THREAD

**Issue by marcel0ll** [cristiadu/cristiadu.github.io#11]
Opa Cris, vi seu site novo e achei "muito azul", fica aqui minha sugestao. 

Atual:

![screencapture-cristianofaustino-me-2021-05-02-10_07_49](https://user-images.githubusercontent.com/2592018/116814302-a03b0580-ab2e-11eb-949b-e97a614db78f.png)

Sugestao:

![screencapture-cristianofaustino-me-2021-05-02-10_07_15](https://user-images.githubusercontent.com/2592018/116814306-a630e680-ab2e-11eb-9ec4-a9e1d73f1abd.png)

**Comment by cristiadu** [comment]
@marcel0ll eu não sou muito fã de fundo branco em websites, embora concordo o tema antigo estava muito azul.

Eu mudei o atual hoje para outro esquema, com uma cor mais clara de fundo, mas sem ser full branco.

Tô usando essa tool para criar matching color palletes aliás: https://coolors.co/1b2f33-28502e-47682c-8c7051-ef3054
